### ISSUE TITLE
Ошибки.

### ISSUE THREAD

**Issue by SimpleUUsser** [bubnenkoff/dlang.ru#14]
[Ошибка №1]
Исходный текст: Если нам потребуется выполнить импорт модуля baz, расположенного в подпакете bar пакета **baz**, мы просто укажем путь до него через точку: `import foo.bar.baz;`
Исправленный вариант:
Если нам потребуется выполнить импорт модуля baz, расположенного в подпакете bar пакета **foo**, мы просто укажем путь до него через точку: `import foo.bar.baz;`

[Ошибка №2]
Исходный текст: Для получения адреса переменной используется символ а**с**персанда &.
Исправленный вариант: Для получения адреса переменной используется символ а**м**персанда &.

[Ошибка №3]
Исходный текст: != проверка на неравенство. Если левая и правая части не совпадают, то будет возвращено значение **false**, в противном случае будет возвращено **true**."
Исправленный вариант: != проверка на неравенство. Если левая и правая части не совпадают, то будет возвращено значение **true**, в противном случае будет возвращено **false**.

P.S Ctrl + F

**Comment by SimpleUUsser** [comment]
[Ошибка №4]
В ### Цикл while.
Первый пример не соответствует приведенному ниже результату.

**Comment by SimpleUUsser** [comment]
[Ошибка №5]
Исходный текст: **Значительна** часть библиотек реализовывает свои классы исключений, унаследованные от базового Exception. 
Исправленный вариант: **Значительная** часть библиотек реализовывает свои классы исключений, унаследованные от базового Exception.

**Comment by bubnenkoff** [comment]
@SimpleUUsser спасибо большое, я как только руки доберутся сразу все исправлю. К сожалению катастрофически не хватает. В формате пул-реквеста мне буде проще имзенения принять.
