### ISSUE TITLE
Разделение книги на отдельные файлы

### ISSUE THREAD

**Issue by dmi7ry** [bubnenkoff/dlang.ru#2]
Сейчас всё свалено в один файл, что не удобно ни для навигации, ни для чтения, ни для редактирования.

**Comment by bubnenkoff** [comment]
Тут идея как раз была в том, чтобы был один файл т.к. разбивка только
усложняет процесс редактирования. Вряд ли Александреску писал книгу по
частям

вт, 8 авг. 2017 г. в 8:27, Dmitry <notifications@github.com>:

**Comment by dmi7ry** [comment]
«Большие» книги пишутся по-другому (а тем более, когда автор один). Он мог её вообще в Ворде писать или любом другом редакторе, а разбивку/редактирование выполняли другие люди в специализированном издательском софте.

В случае онлайн (и гитхаба) гораздо проще работать со множеством небольших файлов.
Например, кто-то занимается вычиткой/редактурой, а вы тем временем захотели поменять что-то в нескольких местах книги. Итог - каждому участнику необходимо постоянное отслеживание всех коммитов/изменений и постоянное разрешение конфликтов версий.

И вы знаете такие примеры - [книга Али Чихрели](https://bitbucket.org/acehreli/ddili/src/70b404c0cf173b200177c84731fa638624d4761b/src/ders/d.en/?at=master), [D Idioms](https://github.com/p0nce/d-idioms/tree/gh-pages/idioms) и другие.

На первом примере - результат генерируется в один файл (pdf, электронные книги и т.п.), или структурировано (в HTML). Точно так же может быть и у вас, но работать проще именно с разными файлами.

**Comment by bubnenkoff** [comment]
Я думаю что книга вряд ли будет таким проектом который будет получать десятки коммитов в день. Поэтому я хотел бы оставить все в виде одного большого файла.

**Comment by dmi7ry** [comment]
Что же, ваше право.
