### ISSUE TITLE
Некорректный Markdown синтаксис

### ISSUE THREAD

**Issue by dmi7ry** [bubnenkoff/dlang.ru#3]
Пропущены пробелы во многих заголовках - между # и текстом заголовка.
Пропущены отделяющие пустые строки между разными заголовками (также между заголовками и текстом).

Как понимаю, это просто из-за «сырости» текста, а не из-за особенностей парсера и т.п.
Могу помочь исправить форматирование, если вы разделите книгу по отдельным файлам.

**Comment by bubnenkoff** [comment]
Угу именно так оно и есть. Писалось все в Sublime без особой оглядки на стандарты.

Касательно вопроса почему я готовый парсер не взял -- я не смог разобраться как его исправить под мои нужды. Чтобы он к примеру div'ы с нужными ID генерировал.

**Comment by dmi7ry** [comment]
>  Писалось все в Sublime без особой оглядки на стандарты.

Проверил несколько плагинов - да, они показывают результат нормально, а вот если здесь, на гитхабе, открыть исходник на редактирование и нажать Preview, то все проблемы и вылезают.

> Чтобы он к примеру div'ы с нужными ID генерировал.

Можно спросить у автора, написав непосредственно на email (в профиле указан).

**Comment by shpinog** [comment]
Почему не использовать gitbook?

**Comment by bubnenkoff** [comment]
@shpinog потому что есть стремление к консолидации и очень не хочется разносить все по разным местам.

**Comment by shpinog** [comment]
Можно вроде отсюда устроить синхронизацию туда, и пилить там и здесь.

**Comment by bubnenkoff** [comment]
нет времени синхронизацию туда-сюда делать. Пока продолжу тут. Далее парсер постараюсь переписать.
