### ISSUE TITLE
Ошибки в тексте

### ISSUE THREAD

**Issue by aburuss** [bubnenkoff/dlang.ru#6]
Прилагаю в файле замеченные ошибки и неточности в главе "Система типов в D". 
[система типов D.docx](https://github.com/bubnenkoff/dlang.ru/files/1273335/D.docx)

**Comment by aburuss** [comment]
Главу "Система типов D" проверять закончил, прилагаю файл с тем, что еще нашел. 
[система типов D - 2.docx](https://github.com/bubnenkoff/dlang.ru/files/1273940/D.-.2.docx)

**Comment by bubnenkoff** [comment]
исправил, спасибо
