### ISSUE TITLE
Не могу распарсить.

### ISSUE THREAD

**Issue by shpinog** [bubnenkoff/dlang.ru#7]
> Теперь после сохранение модуля foo.d, мы сможем получить к данным в нем из модуля, содержащего точку входа, путем вызова в начале import foo;. Обратите внимание, что все импорты работают исключительно внутри единичного модуля.

В книге много мест, где описание наоборот, запутывает и уводит от понимания.

**Comment by bubnenkoff** [comment]
переписал
