### ISSUE TITLE
Ошибки в тексте

### ISSUE THREAD

**Issue by aburuss** [bubnenkoff/dlang.ru#9]
Прилагаю в файле замеченные ошибки начиная от раздела «Арифметические операторы» и до 2 главы и с начала 1 главы до "Системы типов в D".

Таким образом, бегло проверена первая глава по состоянию на 07.09.2017.

[Правка, начиная от раздела «Арифметические операторы» и до 2 главы.docx](https://github.com/bubnenkoff/dlang.ru/files/1284123/2.docx)

[правка с 1 главы до системы типов.docx](https://github.com/bubnenkoff/dlang.ru/files/1284536/1.docx)

**Comment by bubnenkoff** [comment]
Спасибо, исправления внес.
